services:
  broker:
    build: ./mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Chicago
      - URL=mqtt.chem.wisc.edu
      - VALIDATION=http
      - SUBDOMAINS=www,
    volumes:
      - ./nginx/conf:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

