services:
  broker:
    build: ./mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
  swag:
    image: nginx:mainline
    volumes:
      - ./source:/usr/share/nginx/html
    ports:
      - 80:80
    restart: unless-stopped

