version: '3.3'

services:
  broker:
    build: ./mosquitto
    ports:
      - 1883:1883
  db:
    build: ./influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    env_file:
      - ./influxdb.env
  write-influx:
    build: ./write-influx
    depends_on:
      - broker
      - db
    env_file:
      - ./influxdb.env
  web:
    build: ./web
    ports:
      - 8080:80
    depends_on:
      - broker
      - db
      - write-influx

volumes:
  influxdb:
