services:
  broker:
    build: ./mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
  web:
    build: ./web
    restart: unless-stopped
    depends_on:
      - broker
      - db
      - write-influx

